services:

  mongo:
    image: mongo:5.0.2
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongo_root_username
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongo_root_password
      MONGO_INITDB_DATABASE: admin
      DB_NAME: $DB_NAME
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
    volumes:
      - mongo-data:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
    secrets:
      - mongo_root_username
      - mongo_root_password

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 10190:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'

      ME_CONFIG_OPTIONS_EDITORTHEME: 'dracula'

      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_AUTH_USERNAME_FILE : /run/secrets/mongo_root_username
      ME_CONFIG_MONGODB_AUTH_PASSWORD_FILE: /run/secrets/mongo_root_password

      ME_CONFIG_MONGODB_ADMINUSERNAME_FILE: /run/secrets/mongo_root_username
      ME_CONFIG_MONGODB_ADMINPASSWORD_FILE: /run/secrets/mongo_root_password

      ME_CONFIG_BASICAUTH_USERNAME_FILE: /run/secrets/mongo-express_username
      ME_CONFIG_BASICAUTH_PASSWORD_FILE: /run/secrets/mongo-express_password

    secrets:
      - mongo_root_username
      - mongo_root_password
      - mongo-express_username
      - mongo-express_password
    depends_on:
      - mongo

secrets:
  mongo_root_username:
    file: ./secrets/.mongo_root_username
  mongo_root_password:
    file: ./secrets/.mongo_root_password
  mongo-express_username:
    file: ./secrets/.mongo-express_username
  mongo-express_password:
    file: ./secrets/.mongo-express_password

volumes:
  mongo-data: